Repository Pickle-Tave/Pickle-BE, pull requests merged in 2024-06, with the labels that each got.

#42 chore: CI/CD 파이프라인 구축
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  task-definition.json
Labels: :wrench: chore

#55 chore: Spring Actuator 설정
  build.gradle
  src/main/java/com/api/pickle/global/config/security/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: :wrench: chore

#53 feat: 공유 앨범 전환 로직 구현
  src/main/java/com/api/pickle/domain/album/application/AlbumService.java
  src/main/java/com/api/pickle/domain/album/domain/Album.java
  src/main/java/com/api/pickle/domain/participant/dao/ParticipantRepository.java
  src/main/java/com/api/pickle/domain/participant/domain/HostStatus.java
  src/main/java/com/api/pickle/domain/participant/domain/Participant.java
  src/main/java/com/api/pickle/domain/sharedalbum/api/SharedAlbumController.java
  src/main/java/com/api/pickle/domain/sharedalbum/application/SharedAlbumService.java
  src/main/java/com/api/pickle/domain/sharedalbum/dao/SharedAlbumRepository.java
  src/main/java/com/api/pickle/domain/sharedalbum/domain/SharedAlbum.java
  src/main/java/com/api/pickle/domain/sharedalbum/dto/request/SwitchToSharedAlbumRequest.java
  src/main/java/com/api/pickle/domain/sharedalbum/dto/response/SharedLinkResponse.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
  src/main/java/com/api/pickle/global/util/RandomUtil.java
Labels: :sparkles: feature

#59 feat; 앨범명 수정 로직 구현
  src/main/java/com/api/pickle/domain/album/api/AlbumController.java
  src/main/java/com/api/pickle/domain/album/application/AlbumService.java
  src/main/java/com/api/pickle/domain/album/domain/Album.java
  src/main/java/com/api/pickle/domain/album/dto/request/UpdateAlbumRequest.java
  src/main/java/com/api/pickle/domain/album/dto/response/UpdateAlbumResponse.java
Labels: :sparkles: feature

#61 feat: 공유 앨범 참여 api 구현
  src/main/java/com/api/pickle/domain/sharedalbum/api/SharedAlbumController.java
  src/main/java/com/api/pickle/domain/sharedalbum/application/SharedAlbumService.java
  src/main/java/com/api/pickle/domain/sharedalbum/dao/SharedAlbumRepository.java
  src/main/java/com/api/pickle/domain/sharedalbum/dto/request/SharedAlbumParticipateRequest.java
  src/main/java/com/api/pickle/domain/sharedalbum/dto/response/SharedAlbumParticipateResponse.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
Labels: :sparkles: feature

#62 feat: 앨범 검색 기능 구현
  build.gradle
  src/main/java/com/api/pickle/domain/album/api/AlbumController.java
  src/main/java/com/api/pickle/domain/album/application/AlbumService.java
  src/main/java/com/api/pickle/domain/album/dao/AlbumRepository.java
  src/main/java/com/api/pickle/domain/album/dao/AlbumRepositoryCustom.java
  src/main/java/com/api/pickle/domain/album/dao/AlbumRepositoryImpl.java
  src/main/java/com/api/pickle/domain/album/dto/response/AlbumSearchResponse.java
  src/main/java/com/api/pickle/global/config/querydsl/QueryDslConfig.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
Labels: :sparkles: feature

#68 chore: redis 설정
  build.gradle
  src/main/java/com/api/pickle/infra/config/properties/PropertiesConfig.java
  src/main/java/com/api/pickle/infra/config/redis/RedisConfig.java
  src/main/java/com/api/pickle/infra/config/redis/RedisProperties.java
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
Labels: :wrench: chore

#70 feat: 리프레시 토큰이 redis에서 동작되도록 수정
  src/main/java/com/api/pickle/domain/auth/application/JwtTokenService.java
  src/main/java/com/api/pickle/domain/auth/dao/RefreshTokenRepository.java
  src/main/java/com/api/pickle/domain/auth/domain/RefreshToken.java
  src/main/java/com/api/pickle/domain/auth/dto/RefreshTokenDto.java
  src/main/java/com/api/pickle/global/util/JwtUtil.java
Labels: :sparkles: feature

#71 chore: JaCoCo 설정
  build.gradle
  src/test/java/com/api/pickle/PickleApplicationTests.java
  src/test/resources/application-test.yml
Labels: :wrench: chore

#81 chore: Docker Compose 추가
  .github/workflows/deploy.yml
  docker-compose.yml
  src/main/resources/application-redis.yml
  task-definition.json
Labels: :wrench: chore

#84 hotfix: 배포 환경에서 Redis 서버가 종료되는 에러 수정
  src/main/resources/application-redis.yml
  task-definition.json
Labels: :bug: bug

#85 fix: 본인 소유 앨범만 검색 필터 적용되도록 수정
  src/main/java/com/api/pickle/domain/album/application/AlbumService.java
  src/main/java/com/api/pickle/domain/album/dao/AlbumRepositoryCustom.java
  src/main/java/com/api/pickle/domain/album/dao/AlbumRepositoryImpl.java
Labels: :bug: bug

#90 feat: 앨범 목록 조회 및 검색 필터 적용 시 무한 스크롤 기능 구현
  src/main/java/com/api/pickle/domain/album/api/AlbumController.java
  src/main/java/com/api/pickle/domain/album/application/AlbumService.java
  src/main/java/com/api/pickle/domain/album/dao/AlbumRepositoryCustom.java
  src/main/java/com/api/pickle/domain/album/dao/AlbumRepositoryImpl.java
Labels: :sparkles: feature

#93 feat: 즐겨찾기 기능 구현
  src/main/java/com/api/pickle/PickleApplication.java
  src/main/java/com/api/pickle/domain/album/api/AlbumController.java
  src/main/java/com/api/pickle/domain/album/application/AlbumService.java
  src/main/java/com/api/pickle/domain/bookmark/api/BookmarkController.java
  src/main/java/com/api/pickle/domain/bookmark/application/BookmarkService.java
  src/main/java/com/api/pickle/domain/bookmark/application/RedisDatabaseSyncService.java
  src/main/java/com/api/pickle/domain/bookmark/dao/BookmarkRepository.java
  src/main/java/com/api/pickle/domain/bookmark/dao/BookmarkRepositoryCustom.java
  src/main/java/com/api/pickle/domain/bookmark/dao/BookmarkRepositoryImpl.java
  src/main/java/com/api/pickle/domain/bookmark/domain/Bookmark.java
  src/main/java/com/api/pickle/domain/bookmark/domain/MarkStatus.java
  src/main/java/com/api/pickle/domain/bookmark/dto/response/MarkedResponse.java
  src/main/java/com/api/pickle/domain/participant/domain/Participant.java
  src/main/java/com/api/pickle/global/common/constants/RedisConstants.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
  src/main/java/com/api/pickle/infra/config/redis/RedisConfig.java
  src/main/java/com/api/pickle/infra/config/redis/RedisService.java
Labels: :sparkles: feature

#96 fix: 이미지 업로드 로직 수정
  src/main/java/com/api/pickle/domain/image/api/ImageController.java
  src/main/java/com/api/pickle/domain/image/application/ImageService.java
  src/main/java/com/api/pickle/domain/image/domain/Image.java
  src/main/java/com/api/pickle/domain/image/dto/request/AlbumImageCreateRequest.java
  src/main/java/com/api/pickle/domain/image/dto/request/PresignedUrlRequest.java
  src/main/java/com/api/pickle/domain/image/dto/response/PresignedUrlResponse.java
Labels: :bug: bug

#98 feat: FastAPI 서버 api 호출을 통한 이미지 분류 기능 구현
  src/main/java/com/api/pickle/domain/image/api/ImageController.java
  src/main/java/com/api/pickle/domain/image/application/ImageService.java
  src/main/java/com/api/pickle/domain/image/dto/request/ImageClassificationRequest.java
  src/main/java/com/api/pickle/domain/image/dto/response/ClassifiedImageResponse.java
  src/main/java/com/api/pickle/global/config/feign/FeignConfig.java
  src/main/java/com/api/pickle/global/config/feign/KakaoFeignConfig.java
  src/main/java/com/api/pickle/infra/config/fastapi/FastAPIProperties.java
  src/main/java/com/api/pickle/infra/config/feign/ImageClassificationClient.java
  src/main/java/com/api/pickle/infra/config/feign/KakaoLoginClient.java
  src/main/java/com/api/pickle/infra/config/properties/PropertiesConfig.java
  src/main/resources/application-fastapi.yml
  src/main/resources/application.yml
  task-definition.json
Labels: :sparkles: feature

#100 hotfix: 앨범 조회 및 검색 시 redis 데이터가 반영되지 않는 부분 수정
  src/main/java/com/api/pickle/domain/album/application/AlbumService.java
  src/main/java/com/api/pickle/domain/bookmark/application/BookmarkService.java
  src/main/java/com/api/pickle/domain/bookmark/application/RedisDatabaseSyncService.java
  src/main/java/com/api/pickle/domain/bookmark/dao/BookmarkRepositoryCustom.java
  src/main/java/com/api/pickle/domain/bookmark/dao/BookmarkRepositoryImpl.java
  src/main/java/com/api/pickle/domain/bookmark/dto/RedisBookmarkStatusDto.java
  src/main/java/com/api/pickle/global/common/constants/RedisConstants.java
Labels: :ambulance: hotfix
