Repository Pickle-Tave/Pickle-BE, pull requests merged in 2024-05, with the labels that each got.

#12 feat : 예외 처리 로직 구현
  src/main/java/com/api/pickle/global/.gitkeep
  src/main/java/com/api/pickle/global/common/GlobalResponse.java
  src/main/java/com/api/pickle/global/error/ErrorResponse.java
  src/main/java/com/api/pickle/global/error/GlobalExceptionHandler.java
  src/main/java/com/api/pickle/global/error/exception/CustomException.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
Labels: :fire: Feature

#13 feat : 공통 응답 로직 구현
  src/main/java/com/api/pickle/global/common/GlobalResponse.java
  src/main/java/com/api/pickle/global/common/GlobalResponseAdvice.java
Labels: :fire: Feature

#15 Feat/11 swagger setting
  build.gradle
  src/main/java/com/api/pickle/domain/member/domain/Member.java
  src/main/java/com/api/pickle/global/config/SwaggerConfig.java
Labels: :fire: Feature, 최현태

#17 feat: swagger 설정
  build.gradle
  src/main/java/com/api/pickle/domain/member/domain/Member.java
  src/main/java/com/api/pickle/global/config/SwaggerConfig.java
Labels: :fire: Feature, 최현태

#20 feat: S3 Swagger 추가
  src/main/java/com/api/pickle/infra/s3/api/AwsS3Controller.java
  src/main/java/com/api/pickle/infra/s3/dto/response/PresignedUrlResponse.java
Labels: :fire: Feature, 최현태

#25 feat: 카카오 소셜 로그인 api 구현
  build.gradle
  src/main/java/com/api/pickle/PickleApplication.java
  src/main/java/com/api/pickle/domain/auth/api/AuthController.java
  src/main/java/com/api/pickle/domain/auth/application/AuthService.java
  src/main/java/com/api/pickle/domain/auth/application/IdTokenVerifier.java
  src/main/java/com/api/pickle/domain/auth/application/JwtTokenService.java
  src/main/java/com/api/pickle/domain/auth/application/KakaoService.java
  src/main/java/com/api/pickle/domain/auth/dao/RefreshTokenRepository.java
  src/main/java/com/api/pickle/domain/auth/domain/RefreshToken.java
  src/main/java/com/api/pickle/domain/auth/dto/request/AuthCodeRequest.java
  src/main/java/com/api/pickle/domain/auth/dto/request/KakaoTokenRequest.java
  src/main/java/com/api/pickle/domain/auth/dto/response/KakaoTokenResponse.java
  src/main/java/com/api/pickle/domain/auth/dto/response/TokenPairResponse.java
  src/main/java/com/api/pickle/domain/imagetag/domain/ImageTag.java
  src/main/java/com/api/pickle/domain/member/dao/MemberRepository.java
  src/main/java/com/api/pickle/domain/member/domain/Member.java
  src/main/java/com/api/pickle/domain/member/domain/MemberRole.java
  src/main/java/com/api/pickle/domain/member/domain/MemberStatus.java
  src/main/java/com/api/pickle/domain/member/domain/OauthInfo.java
  src/main/java/com/api/pickle/global/common/constants/SecurityConstants.java
  src/main/java/com/api/pickle/global/common/response/GlobalResponse.java
  src/main/java/com/api/pickle/global/common/response/GlobalResponseAdvice.java
  src/main/java/com/api/pickle/global/config/feign/KakaoFeignConfig.java
  src/main/java/com/api/pickle/global/error/GlobalExceptionHandler.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
  src/main/java/com/api/pickle/global/util/JwtUtil.java
  src/main/java/com/api/pickle/infra/config/feign/KakaoLoginClient.java
  src/main/java/com/api/pickle/infra/config/jwt/JwtProperties.java
  src/main/java/com/api/pickle/infra/config/oauth/KakaoProperties.java
  src/main/java/com/api/pickle/infra/config/properties/PropertiesConfig.java
  src/main/resources/application.yml
Labels: :fire: Feature

#28 feat : 토큰 검증 로직 구현
  src/main/java/com/api/pickle/domain/auth/api/AuthController.java
  src/main/java/com/api/pickle/domain/auth/application/AuthService.java
  src/main/java/com/api/pickle/domain/auth/application/JwtTokenService.java
  src/main/java/com/api/pickle/domain/auth/domain/RefreshToken.java
  src/main/java/com/api/pickle/domain/auth/dto/AccessTokenDto.java
  src/main/java/com/api/pickle/domain/auth/dto/RefreshTokenDto.java
  src/main/java/com/api/pickle/domain/auth/dto/request/RefreshRequest.java
  src/main/java/com/api/pickle/global/common/constants/SecurityConstants.java
  src/main/java/com/api/pickle/global/config/security/WebSecurityConfig.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
  src/main/java/com/api/pickle/global/security/JwtAuthenticationFilter.java
  src/main/java/com/api/pickle/global/util/JwtUtil.java
  src/main/java/com/api/pickle/global/util/MemberUtil.java
  src/main/java/com/api/pickle/global/util/SecurityUtil.java
Labels: :fire: Feature

#30 feat : swagger jwt 인증 설정 추가
  src/main/java/com/api/pickle/global/config/swagger/SwaggerConfig.java
Labels: :fire: Feature

#31 Fix/27 image upload
  .gitignore
  src/main/java/com/api/pickle/domain/album/dao/AlbumRepository.java
  src/main/java/com/api/pickle/domain/image/api/ImageController.java
  src/main/java/com/api/pickle/domain/image/application/ImageService.java
  src/main/java/com/api/pickle/domain/image/dao/ImageRepository.java
  src/main/java/com/api/pickle/domain/image/domain/Image.java
  src/main/java/com/api/pickle/domain/image/dto/request/AlbumImageCreateRequest.java
  src/main/java/com/api/pickle/domain/image/dto/response/PresignedUrlResponse.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
  src/main/java/com/api/pickle/infra/config/properties/PropertiesConfig.java
  src/main/java/com/api/pickle/infra/config/s3/S3Config.java
  src/main/java/com/api/pickle/infra/config/s3/S3Properties.java
  src/main/java/com/api/pickle/infra/s3/api/AwsS3Controller.java
  src/main/java/com/api/pickle/infra/s3/application/AwsS3Service.java
  src/main/java/com/api/pickle/infra/s3/config/AwsS3Config.java
  src/main/java/com/api/pickle/infra/s3/dto/response/PresignedUrlResponse.java
Labels: :wrench: Fix
