Repository Pickle-Tave/Pickle-BE, pull requests merged in 2024-07, with the labels that each got.

#110 feat: 개별 앨범 조회 로직 구현
  src/main/java/com/api/pickle/domain/album/api/AlbumController.java
  src/main/java/com/api/pickle/domain/album/application/AlbumService.java
  src/main/java/com/api/pickle/domain/album/dto/response/FetchAlbumImagesResponse.java
  src/main/java/com/api/pickle/domain/image/dao/ImageRepositoryCustom.java
  src/main/java/com/api/pickle/domain/image/dao/ImageRepositoryImpl.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
Labels: :sparkles: feature

#114 feat: 앨범 사진 추가 기능 구현
  src/main/java/com/api/pickle/domain/image/api/ImageController.java
  src/main/java/com/api/pickle/domain/image/application/ImageService.java
  src/main/java/com/api/pickle/domain/image/dao/ImageRepositoryCustom.java
  src/main/java/com/api/pickle/domain/image/dao/ImageRepositoryImpl.java
  src/main/java/com/api/pickle/domain/image/domain/Image.java
  src/main/java/com/api/pickle/domain/image/dto/request/AddImageAlbumRequest.java
Labels: :sparkles: feature

#116 feat: 이미지 삭제 기능 구현
  src/main/java/com/api/pickle/domain/image/api/ImageController.java
  src/main/java/com/api/pickle/domain/image/application/ImageService.java
  src/main/java/com/api/pickle/domain/image/dao/ImageRepositoryCustom.java
  src/main/java/com/api/pickle/domain/image/dao/ImageRepositoryImpl.java
  src/main/java/com/api/pickle/domain/image/dto/request/DeleteImageRequest.java
  src/main/java/com/api/pickle/domain/imagetag/dao/ImageTagRepository.java
  src/main/java/com/api/pickle/domain/imagetag/dao/ImageTagRepositoryCustom.java
  src/main/java/com/api/pickle/domain/imagetag/dao/ImageTagRepositoryImpl.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
Labels: :sparkles: feature

#118 feat: 해시태그로 이미지 검색 로직 구현
  src/main/java/com/api/pickle/domain/album/application/AlbumService.java
  src/main/java/com/api/pickle/domain/image/api/ImageController.java
  src/main/java/com/api/pickle/domain/image/application/ImageService.java
  src/main/java/com/api/pickle/domain/image/dao/ImageRepositoryCustom.java
  src/main/java/com/api/pickle/domain/image/dao/ImageRepositoryImpl.java
  src/main/java/com/api/pickle/domain/membertag/dao/MemberTagRepository.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
Labels: :sparkles: feature

#123 feat: FCM 기능 추가
  build.gradle
  src/main/java/com/api/pickle/domain/member/api/MemberController.java
  src/main/java/com/api/pickle/domain/member/application/MemberService.java
  src/main/java/com/api/pickle/domain/member/domain/FcmInfo.java
  src/main/java/com/api/pickle/domain/member/domain/Member.java
  src/main/java/com/api/pickle/domain/member/dto/request/.gitkeep
  src/main/java/com/api/pickle/domain/member/dto/request/UpdateFcmTokenRequest.java
  src/main/java/com/api/pickle/domain/member/dto/response/.gitkeep
  src/main/java/com/api/pickle/infra/config/fcm/FcmConfig.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#125 hotfix: 배포 환경에서 FCM Config 빈 생성 오류 수정
  task-definition.json
Labels: :ambulance: hotfix

#130 fix: 해시태그를 설정하지 않은 이미지도 조회되도록 수정
  src/main/java/com/api/pickle/domain/image/dao/ImageRepositoryImpl.java
Labels: :bug: bug

#132 hotfix: ECS Fargate에서 execute-command 사용을 위한 taskRoleArn 추가
  task-definition.json
Labels: :ambulance: hotfix

#136 fix: 공유 앨범 참여 시 앨범 목록에 보이도록 수정
  src/main/java/com/api/pickle/domain/bookmark/application/BookmarkService.java
  src/main/java/com/api/pickle/domain/bookmark/dao/BookmarkRepositoryCustom.java
  src/main/java/com/api/pickle/domain/bookmark/dao/BookmarkRepositoryImpl.java
  src/main/java/com/api/pickle/domain/sharedalbum/application/SharedAlbumService.java
Labels: :bug: bug

#138 hotfix: Redis를 AWS ElastiCache로 전환
  docker-compose.yml
  src/main/java/com/api/pickle/infra/config/redis/RedisConfig.java
  src/main/resources/application-redis.yml
  task-definition.json
Labels: :ambulance: hotfix

#141 feat: 이미지 분류 완료 시 푸시 메시지 발송
  src/main/java/com/api/pickle/domain/image/application/ImageService.java
  src/main/java/com/api/pickle/global/common/constants/FcmConstants.java
  src/main/java/com/api/pickle/infra/config/fcm/FcmService.java
Labels: :sparkles: feature

#140 fix: 만료된 엑세스 토큰에 대한 응답 통일
  src/main/java/com/api/pickle/domain/auth/application/JwtTokenService.java
  src/main/java/com/api/pickle/global/error/exception/ErrorCode.java
  src/main/java/com/api/pickle/global/security/JwtAuthenticationFilter.java
Labels: :sparkles: feature

#143 docs : README 업데이트
  README.md
Labels: 📝docs

#144 chore: SonarCloud 설정
  .github/workflows/deploy.yml
  .github/workflows/develop_pull_request.yml
  build.gradle
  docker-compose-test.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: :wrench: chore

#146 chore: 엔티티 스캔 문제 해결
  .gitignore
  build.gradle
  src/main/java/com/api/pickle/PickleApplication.java
  src/main/java/com/api/pickle/infra/jpa/JpaAuditingConfiguration.java
Labels: :wrench: chore
